import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    let body;
    try {
      body = await req.json();
    } catch {
      return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
    }
    const { title, description, category, repoOwner, repoName, guardianName } = body;

    if (!title || !description || !repoOwner || !repoName) {
      return Response.json({ error: 'Missing required fields: title, description, repoOwner, repoName' }, { status: 400 });
    }

    const { accessToken } = await base44.asServiceRole.connectors.getConnection('github');
    const headers = {
      'Authorization': `Bearer ${accessToken}`,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    };

    const apiBase = `https://api.github.com/repos/${repoOwner}/${repoName}`;

    // 1. Get the repository's default branch
    const repoRes = await fetch(apiBase, { headers });
    if (!repoRes.ok) {
      const err = await repoRes.json();
      return Response.json({ error: `Repository not accessible: ${err.message || repoRes.status}` }, { status: 400 });
    }
    const repoData = await repoRes.json();
    const defaultBranch = repoData.default_branch;

    // 2. Get the HEAD sha of the default branch
    const refRes = await fetch(`${apiBase}/git/ref/heads/${defaultBranch}`, { headers });
    if (!refRes.ok) {
      const err = await refRes.json();
      return Response.json({ error: `Failed to read branch: ${err.message}` }, { status: 400 });
    }
    const refData = await refRes.json();
    const baseSha = refData.object.sha;

    // 3. Create a new branch from the default branch
    const now = new Date();
    const timestamp = now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'update';
    const branchName = `core-update/${timestamp}-${slug}`;

    const createBranchRes = await fetch(`${apiBase}/git/refs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
    });
    if (!createBranchRes.ok) {
      const err = await createBranchRes.json();
      return Response.json({ error: `Failed to create branch: ${err.message}` }, { status: 400 });
    }

    // 4. Commit a changelog markdown file on the new branch
    const dateStr = now.toISOString();
    const mdContent =
      `# Core Update: ${title}\n\n` +
      `- **Date:** ${dateStr}\n` +
      `- **Category:** ${category || 'General'}\n` +
      `- **Guardian:** ${guardianName || 'N/A'}\n` +
      `- **Author:** ${user.full_name || user.email || 'Unknown'}\n\n` +
      `## Description\n\n${description}\n\n` +
      `---\n*Logged via HoloKai Civilization Core*\n`;

    const filePath = `updates/${timestamp}-${slug}.md`;
    const encodedContent = btoa(unescape(encodeURIComponent(mdContent)));

    const createFileRes = await fetch(`${apiBase}/contents/${filePath}`, {
      method: 'PUT',
      headers,
      body: JSON.stringify({
        message: `chore(log): ${title}`,
        content: encodedContent,
        branch: branchName,
      }),
    });
    if (!createFileRes.ok) {
      const err = await createFileRes.json();
      return Response.json({ error: `Failed to commit changelog: ${err.message}` }, { status: 400 });
    }

    // 5. Open a pull request from the new branch into the default branch
    const prBody =
      `## Civilization Core Update\n\n${description}\n\n` +
      `### Metadata\n` +
      `- **Category:** ${category || 'General'}\n` +
      `- **Guardian:** ${guardianName || 'N/A'}\n` +
      `- **Author:** ${user.full_name || user.email || 'Unknown'}\n` +
      `- **Logged:** ${dateStr}\n\n` +
      `---\n*This pull request was automatically generated by the HoloKai Civilization Core.*`;

    const prRes = await fetch(`${apiBase}/pulls`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        title: `[Core Update] ${title}`,
        body: prBody,
        head: branchName,
        base: defaultBranch,
      }),
    });
    if (!prRes.ok) {
      const err = await prRes.json();
      return Response.json({ error: `Failed to open pull request: ${err.message}` }, { status: 400 });
    }
    const prData = await prRes.json();

    return Response.json({
      success: true,
      pullRequestUrl: prData.html_url,
      pullRequestNumber: prData.number,
      branch: branchName,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});