/**
 * HoloKai Core Products Data — Wave 2 Implementation
 */

import {
  HoloKaiProduct,
  PricingTier,
  Product,
  UseCase,
  PricingTierConfig,
  Feature,
  FeatureComparison,
  Testimonial,
  CaseStudy,
  Price,
} from './product';

// HoloKai Core Products
export const holoKaiProducts: Product[] = [
  {
    id: 'research-tier',
    slug: 'research-tier',
    name: 'Research Tier',
    category: 'research',
    holoKaiProduct: 'research-tier',
    description: 'Advanced AI-powered research platform with semantic search, knowledge synthesis, and artifact generation for historians and researchers.',
    href: '/research',
    icon: 'BookOpen',
    featured: true,
    useCases: [
      {
        id: 'uc-research-1',
        title: 'Academic Research',
        description: 'Comprehensive literature review and synthesis across thousands of historical documents',
        idealFor: ['Academics', 'Historians', 'Graduate Students'],
      },
      {
        id: 'uc-research-2',
        title: 'Knowledge Discovery',
        description: 'Uncover hidden connections between historical events, figures, and civilizations',
        idealFor: ['Researchers', 'Writers', 'Documentarians'],
      },
      {
        id: 'uc-research-3',
        title: 'Artifact Analysis',
        description: 'AI-assisted analysis of historical artifacts with contextual insights',
        idealFor: ['Museums', 'Archaeologists', 'Cultural Institutions'],
      },
    ],
    availableTiers: ['free', 'pro', 'enterprise'],
  },
  {
    id: 'voice-services',
    slug: 'voice-services',
    name: 'Voice Services',
    category: 'ai',
    holoKaiProduct: 'voice-services',
    description: 'Natural voice interaction with ancient knowledge through text-to-speech and speech-to-text capabilities.',
    href: '/oracle',
    icon: 'Mic',
    featured: false,
    useCases: [
      {
        id: 'uc-voice-1',
        title: 'Voice Queries',
        description: 'Ask questions naturally and receive spoken responses about history',
        idealFor: ['Accessibility Users', 'Commuters', 'Visual Learners'],
      },
      {
        id: 'uc-voice-2',
        title: 'Audio Content',
        description: 'Convert research articles and historical documents to audio format',
        idealFor: ['Audiobook Listeners', 'Podcasters', 'Educators'],
      },
      {
        id: 'uc-voice-3',
        title: 'Language Learning',
        description: 'Practice pronunciation with ancient language voice models',
        idealFor: ['Language Students', 'Linguists', 'Historians'],
      },
    ],
    availableTiers: ['pro', 'enterprise'],
  },
  {
    id: 'vision',
    slug: 'vision',
    name: 'Vision',
    category: 'ai',
    holoKaiProduct: 'vision',
    description: 'AI-powered visual generation and analysis for creating historical reconstructions and artifact visualizations.',
    href: '/oracle',
    icon: 'Eye',
    featured: false,
    useCases: [
      {
        id: 'uc-vision-1',
        title: 'Historical Reconstructions',
        description: 'Generate accurate visualizations of ancient buildings, cities, and artifacts',
        idealFor: ['Museums', 'Educators', 'Documentary Producers'],
      },
      {
        id: 'uc-vision-2',
        title: 'Artifact Analysis',
        description: 'AI analysis of historical images and artifacts with detailed insights',
        idealFor: ['Archaeologists', 'Conservators', 'Researchers'],
      },
      {
        id: 'uc-vision-3',
        title: 'Content Creation',
        description: 'Create engaging visual content for educational materials and presentations',
        idealFor: ['Teachers', 'Content Creators', 'Publishers'],
      },
    ],
    availableTiers: ['pro', 'enterprise'],
  },
  {
    id: 'oracle',
    slug: 'oracle',
    name: 'Oracle',
    category: 'ai',
    holoKaiProduct: 'oracle',
    description: 'Intelligent conversational AI agent that answers questions about ancient civilizations with contextual understanding.',
    href: '/oracle',
    icon: 'Sparkles',
    featured: true,
    useCases: [
      {
        id: 'uc-oracle-1',
        title: 'Knowledge Q&A',
        description: 'Ask any question about history and receive accurate, contextual answers',
        idealFor: ['Students', 'Researchers', 'Curiosity Seekers'],
      },
      {
        id: 'uc-oracle-2',
        title: 'Research Assistant',
        description: 'Collaborative research partner that helps synthesize complex historical topics',
        idealFor: ['Academics', 'Writers', 'Analysts'],
      },
      {
        id: 'uc-oracle-3',
        title: 'Educational Support',
        description: 'Personalized tutoring and explanations for history students',
        idealFor: ['Teachers', 'Students', 'Lifelong Learners'],
      },
    ],
    availableTiers: ['free', 'pro', 'enterprise'],
  },
  {
    id: 'archive',
    slug: 'archive',
    name: 'Archive',
    category: 'archive',
    holoKaiProduct: 'archive',
    description: 'Secure document management system with version control, semantic search, and tier-based access control.',
    href: '/archive',
    icon: 'Archive',
    featured: false,
    useCases: [
      {
        id: 'uc-archive-1',
        title: 'Document Storage',
        description: 'Secure cloud storage for research papers, historical documents, and artifacts',
        idealFor: ['Researchers', 'Institutions', 'Archivists'],
      },
      {
        id: 'uc-archive-2',
        title: 'Version Control',
        description: 'Track changes and maintain history of document revisions',
        idealFor: ['Collaborative Teams', 'Publishers', 'Researchers'],
      },
      {
        id: 'uc-archive-3',
        title: 'Semantic Search',
        description: 'Find documents by meaning and content, not just keywords',
        idealFor: ['Knowledge Workers', 'Researchers', 'Analysts'],
      },
    ],
    availableTiers: ['free', 'pro', 'enterprise'],
  },
];

// Pricing Tiers
export const pricingTiers: PricingTierConfig[] = [
  {
    id: 'free',
    name: 'Free',
    price: {
      amount: 0,
      currency: 'USD',
      period: 'month',
      displayString: '$0/mo',
    },
    description: 'Perfect for exploring HoloKai capabilities',
    features: [
      {
        id: 'f-oracle-basic',
        name: 'Oracle Access',
        description: 'Basic conversational AI with limited queries',
        availableIn: ['free', 'pro', 'enterprise'],
        icon: 'MessageCircle',
      },
      {
        id: 'f-research-limited',
        name: 'Research Tier',
        description: 'Limited research queries per day',
        availableIn: ['free', 'pro', 'enterprise'],
        icon: 'Search',
      },
      {
        id: 'f-archive-basic',
        name: 'Archive Storage',
        description: 'Up to 1GB document storage',
        availableIn: ['free', 'pro', 'enterprise'],
        icon: 'HardDrive',
      },
    ],
    limits: {
      oracleQueries: 50,
      researchQueries: 20,
      archiveStorage: '1GB',
      voiceMinutes: 0,
      visionGenerations: 0,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    price: {
      amount: 29,
      currency: 'USD',
      period: 'month',
      displayString: '$29/mo',
    },
    description: 'For serious researchers and content creators',
    features: [
      {
        id: 'f-oracle-unlimited',
        name: 'Unlimited Oracle',
        description: 'Unlimited conversational AI queries',
        availableIn: ['pro', 'enterprise'],
        icon: 'MessageCircle',
      },
      {
        id: 'f-research-unlimited',
        name: 'Unlimited Research',
        description: 'Unlimited research queries and synthesis',
        availableIn: ['pro', 'enterprise'],
        icon: 'Search',
      },
      {
        id: 'f-voice-services',
        name: 'Voice Services',
        description: 'Text-to-speech and speech-to-text capabilities',
        availableIn: ['pro', 'enterprise'],
        icon: 'Mic',
      },
      {
        id: 'f-vision-basic',
        name: 'Vision Generation',
        description: '100 visual generations per month',
        availableIn: ['pro', 'enterprise'],
        icon: 'Eye',
      },
      {
        id: 'f-archive-pro',
        name: 'Archive Storage',
        description: 'Up to 50GB document storage',
        availableIn: ['pro', 'enterprise'],
        icon: 'HardDrive',
      },
    ],
    limits: {
      oracleQueries: 'unlimited',
      researchQueries: 'unlimited',
      archiveStorage: '50GB',
      voiceMinutes: 300,
      visionGenerations: 100,
    },
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: {
      amount: 199,
      currency: 'USD',
      period: 'month',
      displayString: '$199/mo',
    },
    description: 'For institutions and teams',
    features: [
      {
        id: 'f-oracle-unlimited',
        name: 'Unlimited Oracle',
        description: 'Unlimited conversational AI queries',
        availableIn: ['pro', 'enterprise'],
        icon: 'MessageCircle',
      },
      {
        id: 'f-research-unlimited',
        name: 'Unlimited Research',
        description: 'Unlimited research queries and synthesis',
        availableIn: ['pro', 'enterprise'],
        icon: 'Search',
      },
      {
        id: 'f-voice-unlimited',
        name: 'Unlimited Voice',
        description: 'Unlimited voice services and custom voices',
        availableIn: ['enterprise'],
        icon: 'Mic',
      },
      {
        id: 'f-vision-unlimited',
        name: 'Unlimited Vision',
        description: 'Unlimited visual generations and custom models',
        availableIn: ['enterprise'],
        icon: 'Eye',
      },
      {
        id: 'f-archive-enterprise',
        name: 'Archive Storage',
        description: 'Unlimited document storage with team collaboration',
        availableIn: ['enterprise'],
        icon: 'HardDrive',
      },
      {
        id: 'f-team-collaboration',
        name: 'Team Collaboration',
        description: 'Shared workspaces and team management',
        availableIn: ['enterprise'],
        icon: 'Users',
      },
      {
        id: 'f-api-access',
        name: 'API Access',
        description: 'Full API access for custom integrations',
        availableIn: ['enterprise'],
        icon: 'Code',
      },
      {
        id: 'f-priority-support',
        name: 'Priority Support',
        description: '24/7 dedicated support and SLA',
        availableIn: ['enterprise'],
        icon: 'Headphones',
      },
    ],
    limits: {
      oracleQueries: 'unlimited',
      researchQueries: 'unlimited',
      archiveStorage: 'unlimited',
      voiceMinutes: 'unlimited',
      visionGenerations: 'unlimited',
    },
  },
];

// Feature Comparison Matrix
export const featureComparison: FeatureComparison = {
  features: [
    {
      id: 'f-oracle-basic',
      name: 'Oracle Access',
      description: 'Conversational AI queries',
      availableIn: ['free', 'pro', 'enterprise'],
      icon: 'MessageCircle',
    },
    {
      id: 'f-research-limited',
      name: 'Research Tier',
      description: 'Research queries and synthesis',
      availableIn: ['free', 'pro', 'enterprise'],
      icon: 'Search',
    },
    {
      id: 'f-voice-services',
      name: 'Voice Services',
      description: 'Text-to-speech and speech-to-text',
      availableIn: ['pro', 'enterprise'],
      icon: 'Mic',
    },
    {
      id: 'f-vision-basic',
      name: 'Vision Generation',
      description: 'AI visual generation',
      availableIn: ['pro', 'enterprise'],
      icon: 'Eye',
    },
    {
      id: 'f-archive-basic',
      name: 'Archive Storage',
      description: 'Document storage and management',
      availableIn: ['free', 'pro', 'enterprise'],
      icon: 'HardDrive',
    },
    {
      id: 'f-team-collaboration',
      name: 'Team Collaboration',
      description: 'Shared workspaces',
      availableIn: ['enterprise'],
      icon: 'Users',
    },
    {
      id: 'f-api-access',
      name: 'API Access',
      description: 'Custom integrations',
      availableIn: ['enterprise'],
      icon: 'Code',
    },
    {
      id: 'f-priority-support',
      name: 'Priority Support',
      description: '24/7 dedicated support',
      availableIn: ['enterprise'],
      icon: 'Headphones',
    },
  ],
  tiers: pricingTiers,
};

// Testimonials
export const testimonials: Testimonial[] = [
  {
    id: 't-1',
    name: 'Dr. Sarah Chen',
    role: 'Professor of Ancient History',
    company: 'Cambridge University',
    quote: 'HoloKai has transformed how I teach. Students can now explore ancient civilizations through natural conversation, making history come alive in ways textbooks never could.',
    rating: 5,
    product: 'oracle',
    tier: 'pro',
  },
  {
    id: 't-2',
    name: 'Marcus Rivera',
    role: 'Documentary Filmmaker',
    company: 'History Channel Productions',
    quote: 'The Vision capabilities are incredible. We generated accurate reconstructions of ancient Rome for our latest series in days instead of months.',
    rating: 5,
    product: 'vision',
    tier: 'enterprise',
  },
  {
    id: 't-3',
    name: 'Emma Thompson',
    role: 'PhD Candidate',
    company: 'Oxford University',
    quote: 'Research Tier helped me synthesize hundreds of academic papers for my dissertation. The semantic search found connections I would have missed.',
    rating: 5,
    product: 'research-tier',
    tier: 'pro',
  },
  {
    id: 't-4',
    name: 'James Okonkwo',
    role: 'Museum Curator',
    company: 'British Museum',
    quote: 'Archive has revolutionized our document management. The semantic search helps researchers find relevant artifacts across our entire collection.',
    rating: 4,
    product: 'archive',
    tier: 'enterprise',
  },
  {
    id: 't-5',
    name: 'Lisa Park',
    role: 'Accessibility Advocate',
    quote: 'Voice Services makes historical knowledge accessible to everyone. I can listen to research articles during my commute.',
    rating: 5,
    product: 'voice-services',
    tier: 'pro',
  },
];

// Case Studies
export const caseStudies: CaseStudy[] = [
  {
    id: 'cs-1',
    title: 'Cambridge University Digital History Initiative',
    description: 'How Cambridge University integrated HoloKai across 50+ history courses, improving student engagement by 40%.',
    thumbnail: '/images/case-studies/cambridge.jpg',
    product: 'oracle',
    outcome: 'Increased student engagement, reduced research time, improved learning outcomes',
    metrics: {
      'Student Engagement': '+40%',
      'Research Time': '-60%',
      'Courses Integrated': '50+',
      'Student Satisfaction': '4.8/5',
    },
  },
  {
    id: 'cs-2',
    title: 'British Museum Digital Archive',
    description: 'Modernizing the British Museum\'s document management with semantic search and AI-powered analysis.',
    thumbnail: '/images/case-studies/british-museum.jpg',
    product: 'archive',
    outcome: 'Faster document retrieval, improved research collaboration, enhanced accessibility',
    metrics: {
      'Search Time': '-75%',
      'Documents Digitized': '100K+',
      'Researcher Satisfaction': '4.7/5',
      'Storage Costs': '-40%',
    },
  },
  {
    id: 'cs-3',
    title: 'History Channel Visual Productions',
    description: 'Using Vision to generate historical reconstructions for documentary series.',
    thumbnail: '/images/case-studies/history-channel.jpg',
    product: 'vision',
    outcome: 'Dramatically reduced production time, improved visual accuracy, cost savings',
    metrics: {
      'Production Time': '-70%',
      'Visual Accuracy': '+35%',
      'Cost Savings': '$500K/year',
      'Episodes Produced': '25+',
    },
  },
  {
    id: 'cs-4',
    title: 'Oxford Research Collaboration',
    description: 'Research Tier enabling cross-institutional collaboration on ancient civilization studies.',
    thumbnail: '/images/case-studies/oxford.jpg',
    product: 'research-tier',
    outcome: 'Accelerated research, improved knowledge synthesis, new discoveries',
    metrics: {
      'Research Speed': '+3x',
      'Collaborations': '20+',
      'Papers Published': '15+',
      'Grant Funding': '+$2M',
    },
  },
  {
    id: 'cs-5',
    title: 'Accessibility for All Initiative',
    description: 'Voice Services making historical knowledge accessible to visually impaired users.',
    thumbnail: '/images/case-studies/accessibility.jpg',
    product: 'voice-services',
    outcome: 'Improved accessibility, expanded user base, positive community impact',
    metrics: {
      'Visually Impaired Users': '5K+',
      'Content Consumed': '100K+ hours',
      'User Satisfaction': '4.9/5',
      'Accessibility Score': 'AAA',
    },
  },
];
