/**
 * @holokai/ui — Mock Data Layer for HoloKai Civilization Research OS
 * Generated by Prototype & Build Agents per Requirement 13
 */

export interface ProductTier {
  id: string;
  name: string;
  tagline: string;
  description: string;
  features: string[];
  ctaLabel: string;
  ctaHref: string;
  badge?: string;
  status: 'active' | 'beta' | 'pipeline';
}

export interface FAQItem {
  id: string;
  question: string;
  answer: string;
  category: 'architecture' | 'epistemology' | 'ai-models' | 'federation' | 'access';
}

export interface TestimonialItem {
  id: string;
  quote: string;
  author: string;
  title: string;
  organization: string;
  location: string;
  avatarUrl?: string;
  verified: boolean;
  epistemicFocus: string;
}

export interface SecuritySpecification {
  id: string;
  title: string;
  description: string;
  standard: string;
  status: 'enforced' | 'certified' | 'compliant';
}

export interface HostingMetric {
  id: string;
  label: string;
  value: string;
  subtext: string;
  trend: 'up' | 'stable';
}

export const HOLOKAI_PRODUCT_TIERS: ProductTier[] = [
  {
    id: 'holokai-research',
    name: 'HoloKai Research',
    tagline: 'Ancient Text Analysis & Historical Synthesis at Scale',
    description: 'Ancient text analysis, artifact generation, and historical research at scale across 5,000+ years of epigraphic codices.',
    features: [
      'Multi-agent synthesis across 16-Volume African Codex',
      'Hieroglyphic, Ge\'ez, and Meroitic script OCR translation',
      'Vector similarity search across archaeological ground-truth',
      'Exportable peer-reviewed LaTeX and C4 research dossiers'
    ],
    ctaLabel: 'Explore Research Suite',
    ctaHref: '/oracle',
    badge: 'Core Engine',
    status: 'active'
  },
  {
    id: 'holokai-voice',
    name: 'HoloKai Voice',
    tagline: 'ElevenLabs-Powered Ancient Language Narration',
    description: 'ElevenLabs-powered narration in ancient languages with voice cloning and synthesis of historical codices.',
    features: [
      'Phonetic reconstruction of Classical Ge\'ez and Middle Egyptian',
      'Griot oral tradition voice cloning with emotive modulation',
      'Real-time streaming audio synthesis with under 120ms latency',
      'Synchronized waveform visualizers with script transcriptions'
    ],
    ctaLabel: 'Listen to Voice Oracle',
    ctaHref: '/voice',
    badge: 'ElevenLabs Integrated',
    status: 'active'
  },
  {
    id: 'holokai-vision',
    name: 'HoloKai Vision',
    tagline: 'Gemini-Powered Manuscript & Artifact Generation',
    description: 'Gemini-powered manuscript and artifact generation with intelligent analysis and 3D spatial reconstruction.',
    features: [
      'Multimodal manuscript analysis via Gemini 2.5/3.0 models',
      'Photogrammetric 3D artifact rendering with Gaussian splatting',
      'Pigment degradation analysis and digital restoration',
      'Epistemic confidence heatmaps on reconstructed architectural models'
    ],
    ctaLabel: 'Open Spatial Studio',
    ctaHref: '/vision',
    badge: 'Gemini Multimodal',
    status: 'active'
  }
];

export const HOLOKAI_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'architecture',
    question: 'What is HoloKai Spatial Research Operating System?',
    answer: 'HoloKai is a civilization-scale, edge-native, AI-augmented research OS designed to digitize, verify, and preserve Pan-African epigraphy, astronomy, oral traditions, and historical codices.'
  },
  {
    id: 'faq-2',
    category: 'epistemology',
    question: 'How does the 6-Tier Epistemic Rigor system work?',
    answer: 'Every claim, manuscript line, or historical event in HoloKai is assigned one of six epistemic classifications: Established, Scholarly Debate, Oral Tradition, Esoteric, Speculative, or Fictional with accompanying vector similarity confidence metrics.'
  },
  {
    id: 'faq-3',
    category: 'ai-models',
    question: 'Can I query the multi-agent Oracle AI engine directly?',
    answer: 'Yes. You can query the Oracle Chamber using natural language to retrieve multi-agent synthesized research dossiers with full primary source citations powered by Gemini and our local Python inference cluster.'
  },
  {
    id: 'faq-4',
    category: 'federation',
    question: 'How are micro-frontends (MFEs) federated across the platform?',
    answer: 'HoloKai uses strict TypeScript contract boundaries and event bus messaging to orchestrate independently deployed product remotes without origin latency or cross-app bundle bloat.'
  },
  {
    id: 'faq-5',
    category: 'access',
    question: 'What ancient languages and scripts are natively supported?',
    answer: 'The system natively transliterates and processes Hieroglyphic Egyptian, Meroitic cursive, Ge\'ez classical manuscripts, Ajami Arabic-script African languages, and Old Nubian epigraphic corpora.'
  },
  {
    id: 'faq-6',
    category: 'architecture',
    question: 'How does HoloKai guarantee 99.9% uptime and low-latency research streaming?',
    answer: 'By leveraging globally distributed Cloudflare Edge Workers, streaming Server-Side Rendering (SSR), multi-layer cache invalidation, and zero-request local state caches.'
  }
];

export const HOLOKAI_TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'test-1',
    quote: 'HoloKai is the first platform that treats Pan-African epigraphy and astronomy with the computational rigor, primary-source attribution, and visual elegance it deserves.',
    author: 'Prof. Cheikh Anta Diop Institute',
    title: 'Chair of African Epigraphy & Archaeoastronomy',
    organization: 'IFAN / UCAD',
    location: 'Dakar, Senegal',
    verified: true,
    epistemicFocus: 'Nile Valley & Timbuktu Astronomy'
  },
  {
    id: 'test-2',
    quote: 'The 6-tier epistemic stance system brings unmatched clarity to distinguishing historical consensus from oral tradition in large-scale computational history.',
    author: 'Dr. Kwesi Appiah',
    title: 'Senior Research Fellow',
    organization: 'African Epigraphy & Digital Humanities Project',
    location: 'Accra, Ghana',
    verified: true,
    epistemicFocus: 'Meroitic & Ge\'ez Epigraphy'
  },
  {
    id: 'test-3',
    quote: 'Integrating ElevenLabs voice synthesis with Gemini vision analysis transformed our museum exhibition into an interactive living memory archive.',
    author: 'Amina El-Sayed',
    title: 'Curator of Digital Collections',
    organization: 'Pan-African Historical Trust',
    location: 'Nairobi, Kenya',
    verified: true,
    epistemicFocus: 'Spatial Artifact 3D Reconstruction'
  }
];

export const HOLOKAI_SECURITY_SPECS: SecuritySpecification[] = [
  {
    id: 'sec-1',
    title: 'End-to-End Cryptographic Proofs',
    description: 'Every synthesized dossier is signed with immutable SHA-256 integrity hashes linking back to scanned primary sources.',
    standard: 'SHA-256 / Ed25519',
    status: 'enforced'
  },
  {
    id: 'sec-2',
    title: 'Enterprise SOC 2 Type II Compliance',
    description: 'Rigorous data governance protocols safeguarding sensitive cultural heritage, private research collections, and institutional queries.',
    standard: 'SOC 2 Type II',
    status: 'certified'
  },
  {
    id: 'sec-3',
    title: 'GDPR & Cultural Data Sovereignty',
    description: 'Strict adherence to global privacy laws and indigenous cultural heritage data provenance frameworks.',
    standard: 'GDPR / CARE Principles',
    status: 'compliant'
  }
];

export const HOLOKAI_HOSTING_METRICS: HostingMetric[] = [
  {
    id: 'metric-1',
    label: 'Global Edge Latency',
    value: '< 45ms',
    subtext: '300+ Edge Points of Presence',
    trend: 'stable'
  },
  {
    id: 'metric-2',
    label: 'Verified Primary Sources',
    value: '5,420+',
    subtext: '16 Comprehensive Volumes',
    trend: 'up'
  },
  {
    id: 'metric-3',
    label: 'Uptime SLA',
    value: '99.99%',
    subtext: 'High Availability Multi-Region',
    trend: 'stable'
  },
  {
    id: 'metric-4',
    label: 'Epistemic Precision',
    value: '98.6%',
    subtext: 'Multi-Agent Consensus Score',
    trend: 'up'
  }
];
